name: "Veripy"
author: "nsavelyeva"
description: "Github Actions to perform static analysis of Python code"
inputs:
  scan:
    description: "execute command - use one of lint/sec/cc/mi/hal/raw/cov"
    required: true
  path:
    description: "path to scan, defaults to current working directory"
    default: ""
    required: false
  options:
    description: "additional options for the chosen scanner"
    default: ""
    required: false
  covgate:
    description: "a threshold for unit test coverage to be used as quality gate (not yet implemented)"
    default: "0"
    required: false
  comment:
    description: "if true, send the comment to the PR"
    default: true
    required: false
  update:
    description: "if true and comment is true, the previously sent comment will be updated otherwise a new comment will be created"
    default: true
    required: false
  token:
    description: "github token, required if comment is true."
    default: ""
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.scan }}
    - ${{ inputs.path }}
    - ${{ inputs.options }}
    - ${{ inputs.covgate }}
    - ${{ inputs.comment }}
    - ${{ inputs.update }}
    - ${{ inputs.token }}
branding:
  icon: "git-pull-request"
  color: "blue"
